version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crypto_meme_agent_db
    environment:
      POSTGRES_USER: memeagent
      POSTGRES_PASSWORD: memeagent
      POSTGRES_DB: crypto_meme_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
    name: crypto_meme_agent_db_data